export const SAVE_FUEL_SAVINGS = 'SAVE_FUEL_SAVINGS';
export const CALCULATE_FUEL_SAVINGS = 'CALCULATE_FUEL_SAVINGS';
export const REGISTER_SUCCESS ="REGISTER_SUCCESS";
export const REGISTER_FAILURE ="REGISTER_FAILURE";
export const LOGIN_FAILURE ="LOGIN_FAILURE";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const BUILD_DATA = "BUILD_DATA";
export const CURRENT_BUILD_DATA = "CURRENT_BUILD_DATA";